const RESIDENCES_CONTENT = [
	{
		id: 1,
		image: "/assets/sample.png",
		label: "P48 - Our First One",
		description:
			"Reside in Prominence. Revel in Nature. 3 BHK Luxury Floors in Sector 48, Gurugram.",
		status: "Sold Out.",
		tags: [
			"Best in class finish",
			"Modular Kitchen",
			"Ground level parking",
		],
		bhk: "3 BHK",
		size: "250 sq. yards",
	},
	{
		id: 2,
		image: "/assets/projects/2/elevation.jpg",
		image_gallery: [
			"/assets/projects/2/elevation1.jpg",
			"/assets/projects/2/elevation2.jpg",
			"/assets/projects/2/elevation3.jpg",
			"/assets/projects/2/elevation4.jpg",
		],
		heading_image: "/assets/projects/2/elevation_night.jpg",
		label: "P-16, South City-1",
		description:
			"Luxurious, modern home, ideal for those who appreciate quality living.",
		status: "Sold Out.",
		tags: [
			"Seismic-resistant structure",
			"Vastu-compliant layout",
			"Striking facade",
			"Two dedicated parking slots per floor",
			"Welcoming entrance reception",
			"Quarters for domestic helpers",
			"Schindler elevator system",
			"Luxurious rooms flooded with natural light and featuring balconies",
			"Captivating interior design and wall paneling",
			"Modern kitchen with separate dry and wet areas",
			"High-end branded bathroom fixtures and fittings",
			"Sensor provision for automatic on/off of electronic devices",
			"Floor lighting provision in the parking area",
			"Internal communication system provision (EPABX)",
			"Automatic start and stop water motors provision for each floor",
			"Premium Italian marble flooring with the option for wooden flooring in one",
		],
		number_of_tags: 4,
		plot_size: "360 sq. yards",
		configuration: "4 BHK + Lounge + Servant",
		area: "South City 1, Gurugram",
		possession: "January 2023",
		detailed_description:
			"This architectural masterpiece is tailored for the discerning elite, emphasizing quality at every stage of its construction. A blend of cutting-edge design and advanced technology, this residence offers the pinnacle of luxury living in the vibrant millennium city of India. It stands as a testament to unparalleled craftsmanship, promising a dream home for individuals across all strata of society seeking the finest living experience in a prime location.",
		highlights: [
			"Situated in the prestigious South City 1, Gurugram",
			"Secure gated community",
			"Lush green landscaped surroundings",
			"Shopping mall and food hub within 8 minutes",
			"Millennium City Metro Station just 5 minutes away",
			"IFFCO Chowk reachable in 10 minutes",
			"Convenient access to IGI Airport, only 20 minutes away",
			"Delhi-Gurgaon Highway accessible within 8 minutes",
			"Proximity to Fortis and Max Hospitals, just 5 minutes away",
			"Reputed schools like KR Mangalam and Shikshantar nearby",
		],
	},
	{
		id: 3,
		image: "/assets/sample.png",
		label: "Modular Heaven in DLF",
		description:
			"Reside in Prominence. Revel in Nature. 4 BHK Luxury Floors in DLF Phase 1, Gurugram.",
		status: "Possession Soon.",
		tags: [
			"Best in class finish",
			"Modular Kitchen",
			"Ground level parking",
		],
		bhk: "4 BHK",
		size: "300 sq. yards",
	},
];

export default RESIDENCES_CONTENT;
