const RESIDENCES_CONTENT = [
	{
		id: 1,
		image: "/assets/projects/1/1.jpg",
		image_gallery: [
			"/assets/projects/1/2.jpg",
			"/assets/projects/1/3.jpg",
			"/assets/projects/1/4.jpg",
			"/assets/projects/1/5.jpg",
			"/assets/projects/1/6.jpg",
			"/assets/projects/1/7.jpg",
			"/assets/projects/1/8.jpg",
		],
		heading_image: "/assets/projects/1/1.jpg",
		label: "Plot No 136, Sector 47",
		description:
			"Sophisticated living meets modern amenities in a prime location.",
		status: "Sold Out.",
		number_of_tags: 8,
		plot_size: "263 sq. Yards",
		configuration: "3 BHK + Lounge + Servant",
		location: "Sector 47, Gurugram",
		possession: "March 2020",
		detailed_description:
			"Situated in Gurugram's bustling sector, our first project redefines sophisticated living, offering modern amenities in a prime location. Catering to discerning individuals, it provides a harmonious blend of convenience and comfort. With close proximity to major transport hubs and commercial centers, residents enjoy easy access to the city's vibrant lifestyle. Experience a new level of living, where every detail is meticulously crafted to exceed expectations.",
		tags: [
			"Seismic Resistance",
			"Vastu Compliant",
			"2 Parking slots per floor",
			"Welcome entrance reception",
			"Quarters for domestic helpers",
			"Modern Kitchen with separate dry and wet areas",
			"High-end bathroom fixtures and fittings",
			"Automatic start and stop water motors provision for each floor",
			"Internal communication system provision (EPABX)",
		],
		highlights: [
			"Secure gated community",
			"Lush green landscaped surroundings",
			"Home to Park Hospital, Sector-47; connected to Medanta Hospital (3 km) and Artemis Hospital (5 km)",
			"3 km from Tau Devi Lal Sports Complex",
			"Located along National Highway-248A (Gurgaon-Sohna Road); 3 km from NH-48",
			"5-6 km from leading business parks on Golf Course Extension Road, Sohna Road, and Golf Course Road",
			"Proximity to DoubleTree by Hilton & Holiday Inn; Radisson Hotel is 4 km away",
			"About 20 km from Indira Gandhi International Airport via NH - 48",
		],
	},
	{
		id: 2,
		image: "/assets/projects/2/elevation.jpg",
		image_gallery: [
			"/assets/projects/2/elevation1.jpg",
			"/assets/projects/2/elevation2.jpg",
			"/assets/projects/2/1.jpg",
			"/assets/projects/2/2.jpg",
			"/assets/projects/2/3.jpg",
			"/assets/projects/2/4.jpg",
			"/assets/projects/2/5.jpg",
			"/assets/projects/2/6.jpg",
			"/assets/projects/2/7.jpg",
			"/assets/projects/2/8.jpg",
		],
		heading_image: "/assets/projects/2/elevation.jpg",
		label: "P-16, South City-1",
		description:
			"Luxurious, modern home, ideal for those who appreciate quality living.",
		status: "Sold Out.",
		number_of_tags: 8,
		plot_size: "360 sq. yards",
		configuration: "4 BHK + Lounge + Servant",
		location: "South City 1, Gurugram",
		possession: "January 2023",
		detailed_description:
			"This architectural masterpiece is tailored for the discerning elite, emphasizing quality at every stage of its construction. A blend of cutting-edge design and advanced technology, this residence offers the pinnacle of luxury living in the vibrant millennium city of India. It stands as a testament to unparalleled craftsmanship, promising a dream home for individuals across all strata of society seeking the finest living experience in a prime location.",
		tags: [
			"Seismic-resistant structure",
			"Vastu-compliant layout",
			"Striking facade",
			"Two dedicated parking slots per floor",
			"Welcoming entrance reception",
			"Quarters for domestic helpers",
			"Schindler elevator system",
			"Luxurious rooms flooded with natural light and featuring balconies",
			"Captivating interior design and wall paneling",
			"Modern kitchen with separate dry and wet areas",
			"High-end branded bathroom fixtures and fittings",
			"Sensor provision for automatic on/off of electronic devices",
			"Floor lighting provision in the parking area",
			"Internal communication system provision (EPABX)",
			"Automatic start and stop water motors provision for each floor",
			"Premium Italian marble flooring with the option for wooden flooring in one",
		],
		highlights: [
			"Situated in the prestigious South City 1, Gurugram",
			"Secure gated community",
			"Lush green landscaped surroundings",
			"Shopping mall and food hub within 8 minutes",
			"Millennium City Metro Station just 5 minutes away",
			"IFFCO Chowk reachable in 10 minutes",
			"Convenient access to IGI Airport, only 20 minutes away",
			"Delhi-Gurgaon Highway accessible within 8 minutes",
			"Proximity to Fortis and Max Hospitals, just 5 minutes away",
			"Reputed schools like KR Mangalam and Shikshantar nearby",
		],
	},
	{
		id: 3,
		image: "/assets/projects/3/elevation.jpg",
		image_gallery: [
			"/assets/projects/3/elevation1.jpg",
			"/assets/projects/3/elevation2.jpg",
			"/assets/projects/3/1.jpg",
			"/assets/projects/3/2.jpg",
			"/assets/projects/3/3.jpg",
			"/assets/projects/3/4.jpg",
			"/assets/projects/3/5.jpg",
			"/assets/projects/3/6.jpg",
			"/assets/projects/3/7.jpg",
			"/assets/projects/3/8.jpg",
			"/assets/projects/3/9.jpg",
			"/assets/projects/3/10.jpg",
			"/assets/projects/3/11.jpg",
			"/assets/projects/3/12.jpg",
			"/assets/projects/3/13.jpg",
		],
		heading_image: "/assets/projects/3/elevation.jpg",
		label: "F-3/9, DLF Phase 1",
		description:
			"Experience next-level luxury living in this sought-after location, offering unparalleled elegance and modern amenities.",
		status: "Possession Given.",
		number_of_tags: 5,
		plot_size: "300 sq. yards",
		configuration: "4 BHK + Lounge + Servant Room",
		location: "DLF Phase 1, Gurugram",
		possession: "February 2024",
		detailed_description:
			"This opulent and exquisite residence is an architectural masterpiece tailored for those who appreciate quality living. It combines cutting-edge design with advanced technology, offering the pinnacle of luxury in Gurugram's vibrant millennium city. With unparalleled craftsmanship and a prime location, it promises a dream home for individuals across all strata of society.",
		tags: [
			"Seismic Resistance for safety in unpredictable conditions",
			"Unparalleled Solid Structure for a lasting quality foundation",
			"Vastu Compliant design principles for harmony",
			"Three Parking Slots per Floor for convenience",
			"Italian Claddings and Sitting Ledge in Bathrooms for elegance and comfort",
			"Quarters for Domestic Helpers for extended household staff needs",
			"Modern Kitchen with All Amenities for contemporary convenience",
			"High-end Bathroom Fixtures and Fittings for luxury",
			"Automatic Start and Stop Water Motors Provision for Each Floor for water supply efficiency",
			"Premium Italian Marble Flooring for sophistication and durability",
			"Video Camera Door Bell for enhanced security",
			"Biometric and Pin-based Entrance Lock for advanced access control",
			"Anti-seepage Treatment in All Bathrooms and Balconies for long-lasting maintenance",
			"Rear Area Fully Covered with Solid MS Pipes for structural integrity and safety",
		],
		highlights: [
			"Secured & Gated Community for safety and privacy",
			"Lush Green Landscaped Surroundings for a serene ambiance",
			"Strategic Location along Mehrauli-Gurgaon Highway and Golf Course Road for proximity to corporate hubs",
			"Convenient Connectivity via Guru Dronacharya Metro Station and Rapid Metro Stations for easy transportation",
			"Nearby DLF Cyber City for shopping and entertainment",
			"Approximately 14 km from IGI Airport for convenient travel",
			"Premium Retail Hub with High-end Shopping Malls Nearby for shopping convenience",
			"Well-connected to Faridabad-Gurgaon Road and NH-48 via MG Road for easy access to roadways",
			"Key Social Amenities Nearby including Schools like Kunskapsskolan and American Montessori, St. Stephens, and Private Hospitals for convenience",
			"Qutub Plaza, a Major Market and Food Hub Nearby for dining and shopping options.",
		],
	},
];

export default RESIDENCES_CONTENT;
